// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzhgyodltkifmxoucekc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aGd5b2RsdGtpZm14b3VjZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTA0NTgsImV4cCI6MjA2NDI4NjQ1OH0.Ox07kF16bO__KG5xeHqsDg5hWvNhwH7s59f_MHqB2VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);